DROP TABLE IF EXISTS CAD_PAGAMENTO_IPTU;

CREATE TABLE CAD_PAGAMENTO_IPTU (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    idCidadao INT NOT NULL,
    ano INT NOT NULL,
    valor DECIMAL(10,2) NOT NULL,
    numeroParcela INT NOT NULL,
    pago BOOLEAN DEFAULT FALSE,
    dataVencimento DATE,
    dataPagamento DATE,
    FOREIGN KEY (idCidadao) REFERENCES CAD_CIDADAO(ID)
);
